#!/usr/bin/env python3
"""Knob explainer for the utility-dctls film look: each knob turned down, left, and turned up, on one clip.

    python3 knob_ladder.py recipes                       # writes knob-ladder-recipes.json, prints the recipe names
    python3 knob_ladder.py sheet <stills_dir> <out.jpg> [--stem img-0006]

The recipes start from BASE in dctl-film-recipes.json and change one DCTL setting each; dctl_film_mini.py renders a
still per recipe on the mini (--recipe-file knob-ladder-recipes.json). The sheet lays them out one row per knob with a
plain-English caption, full frames for tone knobs and 1:1 crops for glow and grain, which vanish when scaled down.

Writer: this file. Reader: Ryan, deciding which way to turn each knob. Fails when wrong: a panel is labelled with a
setting it was not rendered with (every caption is built from the same KNOBS table that builds the recipe).

PRIOR ART: the knobs are settings of github.com/thatcherfreeman/utility-dctls DCTLs (Film Curve, Black Point, Halation,
Film Grain); this file only varies them and lays out the stills.
"""
import copy
import json
import os
import sys

import film_chain

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_RECIPES = os.path.join(HERE, "knob-ladder-recipes.json")
BASE = "rich-halation-grain-400"


def _set_print(r, key, v):
    st = next(s for s in r["stages"] if s["dctl"] == "Film Curve" and s["role"] == "print")
    for c in ("Red", "Green", "Blue"):
        st["params"][f"{c} {key}"] = v


def _black_point(r, nits):
    if nits:
        r["stages"].append({"dctl": "Black Point", "role": "black point fade", "params": {
            "Black Point Nits": nits, "Black Point Slope": 0.5, "Clamp Black": 0, "Draw Chart": 0, "Input Transfer Function": 0}})


def _halation(r, stops):
    next(s for s in r["stages"] if s["dctl"] == "Halation")["params"]["Reflection exposure lost"] = stops


def _grain(r, n):
    next(s for s in r["stages"] if s["dctl"] == "Film Grain")["params"]["Grains Per Pixel"] = n


# key, title, what it does, view ("frame" or "crop-bright" / "crop-mid"), steps: (value, caption); None marks BASE
KNOBS = [
    ("contrast", "PRINT CONTRAST  (Film Curve print gamma)", "how hard the midtones separate: up = punchier, down = softer",
     "frame", lambda r, v: _set_print(r, "Gamma", v), [(2.2, "2.2  softer"), (None, "2.8  now"), (3.4, "3.4  punchier")]),
    ("blacks", "BLACK DEPTH  (Film Curve print D max)", "how black the darkest shadows can get: up = inky, down = milky",
     "frame", lambda r, v: _set_print(r, "D_MAX", v), [(2.6, "2.6  milky blacks"), (None, "3.2  now"), (4.0, "4.0  inky blacks")]),
    ("fade", "FADE  (Black Point DCTL, not used yet)", "lifts only the very bottom, like old faded print: up = more fade",
     "frame", _black_point, [(None, "off  now"), (0.5, "0.5 nits  light fade"), (1.5, "1.5 nits  strong fade")]),
    ("glow", "GLOW  (Halation reflection exposure lost)", "red glow bleeding around bright edges: closer to 0 = more glow",
     "crop-bright", _halation, [(None, "-5 stops  now"), (-3.0, "-3 stops  DCTL default"), (-1.5, "-1.5 stops  strong")]),
    ("grain", "GRAIN  (Film Grain grains per pixel)", "more grains = finer, quieter grain; fewer = coarser, stronger",
     "crop-mid", _grain, [(100, "100  first video"), (None, "400  new"), (1600, "1600  finest")]),
]


def recipe_name(key, value):
    return BASE if value is None else f"knob-{key}-{value}"


def write_recipes():
    base = film_chain.load([BASE])[BASE]
    out = {BASE: base}
    for key, _t, _w, _v, apply, steps in KNOBS:
        for value, caption in steps:
            if value is None:
                continue
            r = copy.deepcopy(base)
            apply(r, value)
            r["why"] = f"Knob ladder: {BASE} with {key} set to {value} ({caption.strip()})."
            out[recipe_name(key, value)] = r
    with open(OUT_RECIPES, "w") as f:
        json.dump({"about": f"Generated by knob_ladder.py from {BASE}; one setting changed per recipe.", "recipes": out}, f, indent=1)
    print(",".join(out))


def sheet(stills, out_path, stem):
    import numpy as np
    from PIL import Image, ImageDraw, ImageFilter, ImageFont

    def still(name):
        return Image.open(os.path.join(stills, f"{stem}-{name}.png")).convert("RGB")

    ref = np.asarray(still(BASE).convert("L")).astype(np.float64)
    detail = np.abs(ref - np.asarray(still("null").convert("L").filter(ImageFilter.GaussianBlur(2))).astype(np.float64))

    def best_window(score):
        h, w = score.shape
        ii = np.pad(score.cumsum(0).cumsum(1), ((1, 0), (1, 0)))
        best, pos = -1e18, (0, 0)
        for y in range(0, h - 360, 20):
            for x in range(0, w - 640, 20):
                s = ii[y + 360, x + 640] - ii[y, x + 640] - ii[y + 360, x] + ii[y, x]
                if s > best:
                    best, pos = s, (x, y)
        return pos

    crops = {"crop-bright": best_window((ref > 200).astype(np.float64)),
             "crop-mid": best_window(((ref > 70) & (ref < 170)).astype(np.float64) - 0.05 * detail)}
    try:
        big = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 30)
        small = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 24)
    except OSError:
        big = small = ImageFont.load_default()
    pad, head, cap = 16, 78, 34
    W = 3 * 640 + 4 * pad
    H = len(KNOBS) * (head + 360 + cap + pad) + pad
    sheet_img = Image.new("RGB", (W, H), (16, 16, 16))
    d = ImageDraw.Draw(sheet_img)
    y = pad
    for key, title, what, view, _apply, steps in KNOBS:
        d.text((pad, y + 4), title, fill=(245, 245, 245), font=big)
        d.text((pad, y + 42), what, fill=(185, 185, 185), font=small)
        for i, (value, caption) in enumerate(steps):
            im = still(recipe_name(key, value))
            if view == "frame":
                tile = im.resize((640, 360), Image.LANCZOS)
            else:
                cx, cy = crops[view]
                tile = im.crop((cx, cy, cx + 640, cy + 360))
            a = np.asarray(im.convert("L")).astype(np.float64)
            lum = np.asarray(im).astype(np.float64) @ np.array([0.2126, 0.7152, 0.0722])
            grain = (a - np.asarray(im.convert("L").filter(ImageFilter.MedianFilter(3))).astype(np.float64)).std()
            stat = f"blacks {np.percentile(lum, 1):.0f}  whites {np.percentile(lum, 99):.0f}  grain {grain:.1f}"
            x = pad + i * (640 + pad)
            sheet_img.paste(tile, (x, y + head))
            now = value is None
            d.rectangle((x - 3, y + head - 3, x + 642, y + head + 362), outline=(230, 190, 60) if now else (16, 16, 16), width=3)
            d.text((x + 4, y + head + 366), caption, fill=(230, 190, 60) if now else (235, 235, 235), font=small)
            d.text((x + 330, y + head + 366), stat, fill=(150, 150, 150), font=small)
        y += head + 360 + cap + pad
    sheet_img.save(out_path, quality=90)
    print("sheet", out_path, "crops", crops)


if __name__ == "__main__":
    if sys.argv[1:2] == ["recipes"]:
        write_recipes()
    elif sys.argv[1:2] == ["sheet"]:
        stem = sys.argv[sys.argv.index("--stem") + 1] if "--stem" in sys.argv else "img-0006"
        sheet(sys.argv[2], sys.argv[3], stem)
    else:
        sys.exit(__doc__)
